Fea accent schema (#56)
* opsz-min accents yellow mark

* changed glyph names of accents to remove 'comb'

comb accents can be added later if needed to fulfill the Glyph
Repertoire (CharSet.txt)

* added UC floating accents

UC set mirrors the lc set
lc set naming is the default (with no suffix)
mark UC in green for short term

currently the ‘stacking accents’ and ‘below’ are named and grouped in
their respective case.  (.uc includes glyphs like dotbelow.uc and
‘breve_hookabove.uc’.  using ‘hookabove’ as the common glyph name)
discuss

* .uc floating accents small adjustments

general shift in y +443
small optical adjustment for taller, wider UC

* removal of scrap glyph for checking accent cluster/cloud

* add buildComposites script

* build new composites

* .uc with horn changed to horn.uc

* changed both .txt and .py for Uhorns and Ohorns

added .uc in composition script and dictionaries for these glyphs:

Ohorn Ohornacute Ohorndotbelow Ohorngrave Ohornhookabove Ohorntilde

Uhorn Uhornacute Uhorndotbelow Uhorngrave Uhornhookabove Uhorntilde

* brevebelow's - fixed reference to prev 'comb' composite

* fix Tbar set width and center horzontalbar

* reconcile dup glyphs in opsz-min

* replaced opsz-min with prev version after error

Traceback (most recent call last):
  File "lib/doodleDocument.pyc", line 165, in _loadFont
  File "lib/fontObjects/doodleFont.pyc", line 71, in loadUFO
  File
"/Applications/FontApps/RoboFont.app/Contents/Resources/lib/python2.7/ro
bofab/ufoLib.py", line 333, in getCharacterMapping
  File
"/Applications/FontApps/RoboFont.app/Contents/Resources/lib/python2.7/ro
bofab/glifLib.py", line 274, in getUnicodes
  File
"/Applications/FontApps/RoboFont.app/Contents/Resources/lib/python2.7/ro
bofab/glifLib.py", line 554, in _fetchUnicodes
IOError: [Errno 2] No such file or directory:
u'/Users/pichotta/Desktop/180325 opsz min
error/Amstelvar-Roman-opsz-min.ufo/glyphs/DZcaron_.glif'

* make accent set the same as opsz-min

* reconciled floating accent set with opsz min and max

* Roman-2 floating accents into outlines

* Roman-2  recente prev comb accents and floating set widths

* Roman-2 remove missing Component References

removing circumflexcomb from circumflex_acute
removing acutecomb from circumflex_acute
removing ringcomb from ring_acute
removing acutecomb from ring_acute

* opsz-min  remove missing Component references

removing circumflexcomb from circumflex_acute
removing acutecomb from circumflex_acute
removing ringcomb from ring_acute
removing acutecomb from ring_acute
removing ringcomb from ring_acute.uc
removing acutecomb from ring_acute.uc
removing circumflexcomb from circumflex_acute.uc
removing acutecomb from circumflex_acute.uc

* opsz-max  remove missing Component references

removing ringcomb from aring
removing circumflexcomb from Hcircumflex
removing horncomb from uhorngrave
removing gravecomb from uhorngrave
removing circumflexcomb_acutecomb from acircumflexacute
removing acutecomb from Yacute
removing brevecomb from obreve
removing gravecomb from Ygrave
removing dblgravecomb from rdblgrave
removing caroncomb from ccaron
removing macroncomb from Ymacron
removing circumflexcomb from Acircumflexdotbelow
removing dotbelowcomb from Acircumflexdotbelow
removing circumflexcomb_acutecomb from Acircumflexacute
removing macroncomb from amacron
removing circumflexcomb_hookabovecomb from Ocircumflexhookabove
removing circumflexcomb_gravecomb from Ocircumflexgrave
removing circumflexcomb_hookabovecomb from acircumflexhookabove
removing commaaccentcomb from Kcommaaccent
removing circumflexcomb from circumflex_acute
removing acutecomb from circumflex_acute
removing tildecomb from Otilde
removing caroncomb from Scaron
removing gravecomb from egrave
removing cedillacomb from ccedilla
removing dotaccentcomb_macroncomb from odotaccentmacron
removing acutecomb from Cacute
removing circumflexcomb from Icircumflex
removing caroncomb from Gcaron
removing commaturnedabovecomb from gcommaaccent
removing dblgravecomb from odblgrave
removing commaaccentcomb from kcommaaccent
removing circumflexcomb_hookabovecomb from Ecircumflexhookabove
removing breveinvertedcomb from Ainvertedbreve
removing circumflexcomb from acircumflex
removing horncomb from Ohorndotbelow
removing dotbelowcomb from Ohorndotbelow
removing hungarumlautcomb from Uhungarumlaut
removing ringcomb from Aring
removing dotaccentcomb from Cdotaccent
removing caroncomb from Rcaron
removing brevecomb_tildecomb from Abrevetilde
removing ringcomb from ring_acute
removing acutecomb from ring_acute
removing gravecomb from Agrave
removing dotaccentcomb from Ldot
removing dotaccentcomb from Edotaccent
removing brevecomb from Abreve
removing breveinvertedcomb from Einvertedbreve
removing circumflexcomb from ocircumflex
removing acutecomb from Lacute
removing breveinvertedcomb from iinvertedbreve
removing dotaccentcomb from Gdotaccent
removing brevecomb from Gbreve
removing dotbelowcomb from odotbelow
removing caroncomb.alt from dcaron
removing dotbelowcomb from Edotbelow
removing caroncomb from scaron
removing horncomb from uhorndotbelow
removing dotbelowcomb from uhorndotbelow
removing circumflexcomb_gravecomb from Ecircumflexgrave
removing dblgravecomb from edblgrave
removing brevecomb from abrevedotbelow
removing dotbelowcomb from abrevedotbelow
removing circumflexcomb_tildecomb from Ecircumflextilde
removing ogonekcomb from Eogonek
removing dotaccentcomb from cdotaccent
removing hookabovecomb from Ihookabove
removing horncomb from Ohorngrave
removing gravecomb from Ohorngrave
removing hookabovecomb from ohookabove
removing ringcomb from Uring
removing horncomb from uhorn
removing dblgravecomb from adblgrave
removing acutecomb from lacute
removing dotbelowcomb from adotbelow
removing gravecomb from ygrave
removing macroncomb from umacron
removing horncomb from ohorndotbelow
removing dotbelowcomb from ohorndotbelow
removing horncomb from Ohornhookabove
removing hookabovecomb from Ohornhookabove
removing circumflexcomb_gravecomb from ecircumflexgrave
removing acutecomb from oacute
removing dotbelowcomb from Odotbelow
removing gravecomb from ograve
removing ringcomb from uring
removing dieresiscomb from edieresis
removing horncomb from uhorntilde
removing tildecomb from uhorntilde
removing circumflexcomb_tildecomb from acircumflextilde
removing horncomb from Ohorn
removing hookabovecomb from ihookabove
removing circumflexcomb_acutecomb from Ecircumflexacute
removing cedillacomb from Scedilla
removing circumflexcomb from gcircumflex
removing circumflexcomb from ecircumflex
removing dotaccentcomb from Idotaccent
removing horncomb from Uhorngrave
removing gravecomb from Uhorngrave
removing hookabovecomb from Ehookabove
removing circumflexcomb from ccircumflex
removing macroncomb from omacron
removing acutecomb from uacute
removing dieresiscomb from ydieresis
removing hookabovecomb from ahookabove
removing commaaccentcomb from ncommaaccent
removing circumflexcomb from Ecircumflexdotbelow
removing dotbelowcomb from Ecircumflexdotbelow
removing horncomb from Uhornacute
removing acutecomb from Uhornacute
removing acutecomb from aeacute
removing gravecomb from agrave
removing dblgravecomb from Odblgrave
removing circumflexcomb_tildecomb from Ocircumflextilde
removing circumflexcomb_tildecomb from ecircumflextilde
removing dieresiscomb from Adieresis
removing dieresiscomb from Odieresis
removing hungarumlautcomb from Ohungarumlaut
removing brevecomb_gravecomb from Abrevegrave
removing circumflexcomb from ucircumflex
removing caroncomb from Ecaron
removing caroncomb.alt from Lcaron
removing commaaccentcomb from Tcommaaccent
removing commaaccentcomb from Ncommaaccent
removing circumflexcomb from icircumflex
removing macroncomb from imacron
removing acutecomb from wacute
removing hookabovecomb from Uhookabove
removing dblgravecomb from Rdblgrave
removing dotaccentcomb_macroncomb from Odotaccentmacron
removing tildecomb from Itilde
removing brevecomb_tildecomb from abrevetilde
removing circumflexcomb_hookabovecomb from ocircumflexhookabove
removing brevecomb from Ubreve
removing circumflexcomb from Ycircumflex
removing horncomb from uhornacute
removing acutecomb from uhornacute
removing horncomb from Uhorndotbelow
removing dotbelowcomb from Uhorndotbelow
removing ogonekcomb from uogonek
removing gravecomb from Wgrave
removing circumflexcomb_tildecomb from ocircumflextilde
removing acutecomb from iacute
removing commaaccentcomb from Rcommaaccent
removing dieresiscomb from Ydieresis
removing ogonekcomb from Aogonek
removing horncomb from uhornhookabove
removing hookabovecomb from uhornhookabove
removing horncomb from Uhorntilde
removing tildecomb from Uhorntilde
removing commaaccentcomb from tcommaaccent
removing breveinvertedcomb from ainvertedbreve
removing circumflexcomb from Jcircumflex
removing cedillacomb from Ccedilla
removing caroncomb.alt from tcaron
removing hookabovecomb from uhookabove
removing horncomb from ohornhookabove
removing hookabovecomb from ohornhookabove
removing commaaccentcomb from lcommaaccent
removing circumflexcomb from Ucircumflex
removing dotbelowcomb from udotbelow
removing dotaccentcomb from ldot
removing brevecomb from abreve
removing acutecomb from racute
removing circumflexcomb from Ocircumflexdotbelow
removing dotbelowcomb from Ocircumflexdotbelow
removing acutecomb from Uacute
removing tildecomb from itilde
removing macroncomb from Emacron
removing dotaccentcomb from edotaccent
removing dieresiscomb_macroncomb from odieresismacron
removing acutecomb from Oslashacute
removing hungarumlautcomb from ohungarumlaut
removing ogonekcomb from Oogonek
removing horncomb from Ohornacute
removing acutecomb from Ohornacute
removing circumflexcomb from Ocircumflex
removing dblgravecomb from udblgrave
removing brevecomb_hookabovecomb from abrevehookabove
removing circumflexcomb from Gcircumflex
removing ogonekcomb from Uogonek
removing tildecomb from Atilde
removing acutecomb from Sacute
removing dotbelowcomb from Idotbelow
removing dotaccentcomb from zdotaccent
removing circumflexcomb from hcircumflex
removing commaaccentcomb from Scommaaccent
removing tildecomb from ntilde
removing horncomb from ohorntilde
removing tildecomb from ohorntilde
removing acutecomb from Zacute
removing acutecomb from Eacute
removing tildecomb from Etilde
removing acutecomb from cacute
removing circumflexcomb from Acircumflex
removing caroncomb from gcaron
removing breveinvertedcomb from rinvertedbreve
removing caroncomb from Ncaron
removing dieresiscomb from Idieresis
removing breveinvertedcomb from Oinvertedbreve
removing breveinvertedcomb from uinvertedbreve
removing brevecomb from Obreve
removing dieresiscomb from udieresis
removing caroncomb from rcaron
removing caroncomb from Ccaron
removing dotbelowcomb from Adotbelow
removing tildecomb from atilde
removing brevecomb_acutecomb from Abreveacute
removing acutecomb from sacute
removing brevecomb from gbreve
removing ringcomb_acutecomb from Aringacute
removing acutecomb from AEacute
removing dotbelowcomb from ydotbelow
removing acutecomb from zacute
removing caroncomb from Tcaron
removing circumflexcomb_hookabovecomb from Acircumflexhookabove
removing hookabovecomb from Ohookabove
removing breveinvertedcomb from Uinvertedbreve
removing gravecomb from Ugrave
removing acutecomb from Racute
removing hungarumlautcomb from uhungarumlaut
removing gravecomb from Egrave
removing tildecomb from Utilde
removing gravecomb from igrave
removing tildecomb from otilde
removing acutecomb from nacute
removing circumflexcomb from Ecircumflex
removing acutecomb from Aacute
removing horncomb from ohorn
removing dieresiscomb from wdieresis
removing circumflexcomb from ycircumflex
removing tildecomb_macroncomb from Otildemacron
removing acutecomb from oslashacute
removing macroncomb from Amacron
removing acutecomb from Oacute
removing dieresiscomb from idieresis
removing breveinvertedcomb from Iinvertedbreve
removing tildecomb from Ytilde
removing commaaccentcomb from Lcommaaccent
removing dblgravecomb from Idblgrave
removing caroncomb from Dcaron
removing gravecomb from ugrave
removing circumflexcomb from ecircumflexdotbelow
removing dotbelowcomb from ecircumflexdotbelow
removing breveinvertedcomb from einvertedbreve
removing dotbelowcomb from Ydotbelow
removing hookabovecomb from Ahookabove
removing brevecomb_acutecomb from abreveacute
removing circumflexcomb_acutecomb from Ocircumflexacute
removing tildecomb_macroncomb from otildemacron
removing cedillacomb from tcedilla
removing dblgravecomb from idblgrave
removing caroncomb from ncaron
removing hookabovecomb from Yhookabove
removing circumflexcomb_gravecomb from acircumflexgrave
removing dieresiscomb from Wdieresis
removing circumflexcomb_gravecomb from ocircumflexgrave
removing caroncomb from Zcaron
removing dieresiscomb_macroncomb from Odieresismacron
removing breveinvertedcomb from Rinvertedbreve
removing acutecomb from yacute
removing caroncomb from ecaron
removing dotbelowcomb from Udotbelow
removing dblgravecomb from Edblgrave
removing cedillacomb from Tcedilla
removing circumflexcomb_tildecomb from Acircumflextilde
removing dotbelowcomb from edotbelow
removing acutecomb from Wacute
removing macroncomb from ymacron
removing dieresiscomb from Udieresis
removing circumflexcomb_gravecomb from Acircumflexgrave
removing circumflexcomb from Scircumflex
removing caroncomb.alt from lcaron
removing ringcomb_acutecomb from aringacute
removing gravecomb from Igrave
removing circumflexcomb from acircumflexdotbelow
removing dotbelowcomb from acircumflexdotbelow
removing circumflexcomb_acutecomb from ocircumflexacute
removing ogonekcomb from aogonek
removing circumflexcomb from scircumflex
removing circumflexcomb from ocircumflexdotbelow
removing dotbelowcomb from ocircumflexdotbelow
removing horncomb from Ohorntilde
removing tildecomb from Ohorntilde
removing circumflexcomb from jcircumflex
removing ogonekcomb from eogonek
removing macroncomb from Umacron
removing tildecomb from utilde
removing tildecomb from Ntilde
removing horncomb from Uhornhookabove
removing hookabovecomb from Uhornhookabove
removing caroncomb from zcaron
removing dieresiscomb from odieresis
removing commaaccentcomb from scommaaccent
removing brevecomb from ebreve
removing horncomb from Uhorn
removing brevecomb_gravecomb from abrevegrave
removing tildecomb from etilde
removing commaaccentcomb from rcommaaccent
removing dotaccentcomb from idotaccent
removing dieresiscomb from Edieresis
removing hookabovecomb from ehookabove
removing hookabovecomb from yhookabove
removing macroncomb from emacron
removing ogonekcomb from oogonek
removing breveinvertedcomb from oinvertedbreve
removing brevecomb from Ibreve
removing commaaccentcomb from Gcommaaccent
removing horncomb from ohorngrave
removing gravecomb from ohorngrave
removing brevecomb from Ebreve
removing dotbelowcomb from idotbelow
removing macroncomb from Omacron
removing ogonekcomb from Iogonek
removing acutecomb from Nacute
removing ogonekcomb from iogonek
removing gravecomb from Ograve
removing circumflexcomb_hookabovecomb from ecircumflexhookabove
removing dblgravecomb from Adblgrave
removing horncomb from ohornacute
removing acutecomb from ohornacute
removing dotaccentcomb from Zdotaccent
removing acutecomb from Iacute
removing brevecomb from ibreve
removing brevecomb from ubreve
removing dotaccentcomb from gdotaccent
removing circumflexcomb from Wcircumflex
removing dieresiscomb from adieresis
removing macroncomb from Imacron
removing circumflexcomb_acutecomb from ecircumflexacute
removing cedillacomb from scedilla
removing acutecomb from aacute
removing circumflexcomb from Ccircumflex
removing brevecomb from Abrevedotbelow
removing dotbelowcomb from Abrevedotbelow
removing acutecomb from eacute
removing dblgravecomb from Udblgrave
removing gravecomb from wgrave
removing circumflexcomb from wcircumflex
removing brevecomb_hookabovecomb from Abrevehookabove
removing tildecomb from ytilde

* centering floating on non-zero set widths

* Update composite script to work within RoboFont

* delete bug with DZcaron Dzcaron dzcaron NJ Nj nj LJ Lj lj

* fix #55 : rebuild DZcaron Dzcaron dzcaron NJ Nj nj LJ Lj lj

* update build composite script to use anchors

* rebuild composites on Roman

* Added some missing floating accents

* ignore anchor y offset

* rebuild Roman composites

* shifted .uc up in 'y'